In [ ]:
import numpy as np
print(np.__version__)
import matplotlib.pylab as plt

1.21.6


# Numpy Basics:


**Exercise #1:** Creating a numpy array with particular value

**Your Task** Create a numpy array with size 2*3 with all elements as 5.

In [ ]:
# YOUR CODE STARTS HERE
arr = np.full((2,3),5)
# YOUR CODE ENDS HERE
print(arr)

[[5 5 5]
 [5 5 5]]


**Exercise #2:** Creating a numpy array with *random* value

**Your Task** Create a numpy array with size 2*3 with all random values

In [ ]:
# YOUR CODE STARTS HERE
rand_arr = np.random.rand(2,3)
# YOUR CODE ENDS HERE
print(rand_arr)

[[0.86862055 0.40468567 0.57110971]
 [0.76942959 0.67792941 0.60900607]]


**Exercise #3:** Basic NumPy operatrions

**Your Task** For the random array `arr`defined above, find the `sum` of all the elements, `mean`, `maximum` and `minimum` value 

In [ ]:
#YOUR CODE STARTS HERE
arr_sum = np.sum(rand_arr)
arr_mean = np.mean(rand_arr)
arr_max = np.max(rand_arr)
arr_min = np.min(rand_arr)
#YOUR CODE ENDS HERE

print(f'sum: {arr_sum}\nmean: {arr_mean}\nmax: {arr_max}\nmin:{arr_min}')

sum: 3.900780997566411
mean: 0.6501301662610685
max: 0.8686205499093984
min:0.40468566682563567


**Exercise #4:** `argmin` and `argmax`

**Your Task** For the random array `arr`defined below:

*   Find the position of maximum and minimum value of above array
*   Find the indices of maximum and minimum value along each of its columns.
*   Find the indices of maximum and minimum value along each of the its rows.



In [ ]:
# Define an array
arr = np.array([[5,12,51,25] ,[25,29,2,27]])
print(f'Array:\n{arr}\n')
# YOUR CODE STARTS HERE
#Find the position of maximum and minimum value of above array
max_idx = np.where(arr == np.max(arr))
min_idx = np.where(arr == np.min(arr))
print(max_idx, min_idx)

#Find the indices of maximum and minimum value along each of its columns.
max_col = np.argmax(arr, axis = 1)
min_col = np.argmax(arr, axis = 1)
print(max_col,min_col)

#Find the indices of maximum and minimum value along each of the its rows.
max_row = np.argmin(arr, axis = 0)
min_row = np.argmin(arr, axis = 0)
print(max_row,min_row)
#YOUR CODE ENDS HERE


Array:
[[ 5 12 51 25]
 [25 29  2 27]]

(array([0]), array([2])) (array([1]), array([2]))
[2 1] [2 1]
[0 0 1 0] [0 0 1 0]
